### PR TITLE
Mongodb support

### PR DESCRIPTION
**Pull request by opsxcq**
Added support for storing pasties on mongodb

### CODE REVIEW

**Comment by cvandeplas** [comment]
Great ! 

Do you think it's also a good idea to implement the save-all option for the mongodb?  (saving all pasties, and not only those that gave an alert) 
See:  https://github.com/opsxcq/pystemon/blob/7abb7d9cb38708ad4d0c96322e6cd72b11bf4622/pystemon.py#L262
and https://github.com/opsxcq/pystemon/blob/7abb7d9cb38708ad4d0c96322e6cd72b11bf4622/pystemon.yaml#L6

**Comment by opsxcq** [comment]
Good idea. But we will have to change how paste is stored on mongo. Paste id must be stored too, as I've read in your code, that for performance reasons, you check if the paste was seen before looking up by it's id.

**Comment by cvandeplas** [comment]
correct. right now the check is only done when stored locally on the disk. The goal is only to not download pasties that have already been downloaded/scanned.

Storing a pastie in a db does not force us to also add the 'caching' feature of looking it up in the db, so that's completely optional.
A major question for storing all vs storing only alerts is how to distinguish both in your database/mongo. I'm not that familiar with mongo, but in a SQL you would put it in another table. In Elastic either another index, or with an extra field or tag in the json to mark it as "alert".

**Comment by opsxcq** [comment]
I would suggest another collection. Maintenance will be easier, no junk
will remain on indexes, and needed size for the indexes will be smaller,
since on alert collection will be the collection that we can use for a lot
of different queries, and archive collection, at this moment will be used
only to search by paste id.

So, we give the user the freedom to use any heavy feature, like full text
search for example in his alert collection and a lot of indexes, but on his
archive collection, just one index on ID for example. That will be a good
balance between performance, semantic (having the same behavior as saving
to a file) and scalability.

What you think about it ?


--
Rafael

**Comment by cvandeplas** [comment]
Good idea. An advanced user will anyway customise everything to his needs. 
Thanks

**Pull request merged**
