### PR TITLE
Pruned pasties already queued

### PR DESCRIPTION
**Pull request by chervaliery**
This pull request prevents adding a pastie in the download queue if it is already in but not yet seen.
Otherwise the size of the queue is incorrect as there are duplicates.

### CODE REVIEW

**Comment by chervaliery** [comment]
Yes but the seen_pasties list is only updated after the pastie has been fetched and processed.

So if the pastie has to be download but still in the queue it will be had again.

Here an example:
There is 4 pasties on the web site, after the get_last_pasties, they are all in the queue and none in the seen list for the moment. There is 4 to download.

```
      +-+           +-+            +-+
      |d|           |a|            | |
      +-+           +-+            +-+
      |c|           |b|            | |
      +-+           +-+            +-+
      |b|           |c|            | |
      +-+           +-+            +-+
      |a|           |d|            | |
      +-+           +-+            +-+

  on the site   in the queue   in the seen list
```

Now, imagine there is 2 new pasties on the site, but only 3 pasties has been fetched and processed (`a`, `b` and `c`) from the previous step. As `c` is in the seen list, it will not be queue again, but as `d` is still in the queue, it will be had again.
```
        +-+           +-+            +-+
        |f|           |d|            |a|
        +-+           +-+            +-+
        |e|           |d|            |b|
        +-+           +-+            +-+
        |d|           |e|            |c|
        +-+           +-+            +-+
        |c|           |f|            | |
        +-+           +-+            +-+

    on the site   in the queue   in the seen list
```

I faced this problem, the processing of each pastie took a long time and the queue growht without limit as 250 new pasties were had to the queue:

```
Jul  8 02:00:05 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 100 pasties to be downloaded.
Jul  8 02:00:45 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 197 pasties to be downloaded.
Jul  8 02:01:30 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 294 pasties to be downloaded.
Jul  8 02:02:16 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 390 pasties to be downloaded.
Jul  8 02:02:59 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 486 pasties to be downloaded.
Jul  8 02:03:41 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 581 pasties to be downloaded.
Jul  8 02:04:25 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 677 pasties to be downloaded.
Jul  8 02:05:08 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 771 pasties to be downloaded.
Jul  8 02:05:48 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 865 pasties to be downloaded.
Jul  8 02:06:33 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 960 pasties to be downloaded.
Jul  8 02:07:17 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 1055 pasties to be downloaded.
Jul  8 02:08:04 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 1148 pasties to be downloaded.
Jul  8 02:08:46 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 1242 pasties to be downloaded.
Jul  8 02:09:33 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 1337 pasties to be downloaded.
Jul  8 02:10:17 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 1434 pasties to be downloaded.
Jul  8 02:11:06 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 1533 pasties to be downloaded.
Jul  8 02:11:59 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 1632 pasties to be downloaded.
Jul  8 02:12:48 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 1731 pasties to be downloaded.
Jul  8 02:13:38 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 1831 pasties to be downloaded.
Jul  8 02:14:30 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 1929 pasties to be downloaded.
Jul  8 02:15:15 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 2029 pasties to be downloaded.
Jul  8 02:16:07 ubu-01 pystemon[19123]: Found 100 new pasties for site pastebin.com_pro. There are now 2128 pasties to be downloaded.
...
```

**Comment by cvandeplas** [comment]
Good point.
Can't we solve it in an easier way remembering that we've "seen" (or queued) it immediately by using the `seen_pastie_and_remember()` function? See this [line](https://github.com/chervaliery/pystemon/blob/523b9592dd8cb679f6bd423ef1b5e4a2de6ff7b4/pystemon.py#L189) .

Before:
```python
            for pastie_id in pasties_ids:
                # check if the pastie was already downloaded
                # and remember that we've seen it
                if self.seen_pastie(pastie_id):
                    # do not append the seen things again in the queue
                    continue
                # pastie was not downloaded yet. Add it to the queue
                if self.pastie_classname:
```
Proposed:
```python
            for pastie_id in pasties_ids:
                # check if the pastie was already downloaded
                # and remember that we've seen it
                if self.seen_pastie_and_remember(pastie_id):
                    # do not append the seen things again in the queue
                    continue
                # pastie was not downloaded yet. Add it to the queue
                if self.pastie_classname:
```

It has been ages I've wrote that code, but I can't recall a reason why I didn't put it in the seen_list immediately.

**Comment by chervaliery** [comment]
This would be the easiest way... But as there is:
```
        if db:
            db.queue.put(pastie)
        return seen
```
in the `seen_pastie_and_remember` function, this won't works before the pastie is fetch.

One possibility would be to change the way pasties are saved.
We already works on the mongo part (related to #88) let see if a huge refactor can solve all the problems.

**Comment by cvandeplas** [comment]
addressed by #90

**Pull request closed without merging**
