### PR TITLE
Define logging level in configuration #99

### PR DESCRIPTION
**Pull request by chervaliery**
The parameter `logging-level` in configuration allows you to choose the logging level of the application, `INFO` is still the default and the `--debug` overwrites it.

### CODE REVIEW

**Comment by chervaliery** [comment]
@cvandeplas, does it look fine for you ?

**Comment by cvandeplas** [comment]
Very nice, thank you.
Would you be able to quickly correct the typo ? "invalide" => "invalid" .

**Comment by chervaliery** [comment]
Sorry for the typo, French guy spotted.

**Comment by cvandeplas** [comment]
pas de soucis, merci !

**Pull request merged**
